# Generated by Django 4.2.4 on 2023-09-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0020_alter_targetname_created_alter_targetname_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('targetlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_targets.targetlist')),
            ],
            bases=('tom_targets.targetlist',),
        ),
    ]
