# Generated by Django 4.2.4 on 2023-09-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0020_alter_targetname_created_alter_targetname_modified'),
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectTargetList',
        ),
        migrations.AlterModelOptions(
            name='projecttargetlist',
            options={'ordering': ('-created', 'name')},
        ),
    ]
