# Generated by Django 4.2.4 on 2023-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgalaxy',
            name='catalog',
            field=models.CharField(default='/data/ghost/GHOST.csv', help_text='CSV file where all columns are stored.', max_length=100),
        ),
    ]
