# Generated by Django 4.2.4 on 2023-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0002_rename_project_projecttargetlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttargetlist',
            name='query',
            field=models.CharField(default='{}', help_text="This project's query submission string for ANTARES.", max_length=1000),
            preserve_default=False,
        ),
    ]
