# Generated by Django 4.2.4 on 2023-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_projecttargetlist_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttargetlist',
            name='sn_type',
            field=models.CharField(default='SN Ia', help_text='The supernova type to check for.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttargetlist',
            name='tns',
            field=models.BooleanField(default=False, help_text='Whether to query TNS catalog'),
            preserve_default=False,
        ),
    ]
