# Generated by Django 4.2.4 on 2023-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_alter_hostgalaxy_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgalaxy',
            name='catalog',
            field=models.CharField(default='/Users/kdesoto/python_repos/vtda-alert-pipeline/src/static/ghost/GHOST.csv', help_text='CSV file where all columns are stored.', max_length=100),
        ),
    ]
